services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raptika_backend
    restart: unless-stopped
    working_dir: /var/www

    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: railway
      DB_USERNAME: root
      DB_PASSWORD: ""

    depends_on:
      db:
        condition: service_started

    networks:
      - raptika_network

  db:
    image: mysql:8.0
    container_name: raptika_mysql
    restart: unless-stopped

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: railway

    ports:
      - "3307:3306"

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - raptika_network

  nginx:
    image: nginx:alpine
    container_name: raptika_nginx
    restart: unless-stopped

    depends_on:
      backend:
        condition: service_started

    ports:
      - "8000:80"

    volumes:
      - .:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - raptika_network

networks:
  raptika_network:
    driver: bridge

volumes:
  db_data: